version: "3"

networks:
  app_network:
    name: app_network

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    container_name: postgresdb
    image: postgres:16.2
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: unifiers123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5433:5432"

  pgadmin:
    container_name: pgadmin01
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - app_network
    depends_on:
      - postgres

volumes:
  postgres-data:
